name: 书旗小说2
on:
  workflow_dispatch:
  schedule:
     - cron: '30 */1 * * *' 
jobs:
  build:
  
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: sngxpro/AutoRunJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install got
          npm install cron
          npm install request
      - name: '【书旗小说】'
        run: |
          node task/shuqi.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
